// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laogbmluuzlsordlbgol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxhb2dibWx1dXpsc29yZGxiZ29sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0ODE5OTYsImV4cCI6MjA1NTA1Nzk5Nn0.GkVSVC0y_HOCjPymPNp4EwvJ7xYsVCM1STMxHiFMYqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);